export const fakeAttendanceData = {
    meetingId: '1234567890',
    participants: [
        { name: 'Alice', attendanceStatus: 'Present', score: 90 },
        { name: 'Bob', attendanceStatus: 'Absent', score: 70 },
        { name: 'Charlie', attendanceStatus: 'Present', score: 85 },
        { name: 'David', attendanceStatus: 'Late', score: 60 },
        { name: 'Eve', attendanceStatus: 'Present', score: 95 },
        { name: 'Frank', attendanceStatus: 'Absent', score: 50 },
        { name: 'Grace', attendanceStatus: 'Present', score: 80 },
        { name: 'Heidi', attendanceStatus: 'Present', score: 75 },
        { name: 'Ivan', attendanceStatus: 'Absent', score: 40 },
        { name: 'Judy', attendanceStatus: 'Late', score: 65 },
        { name: 'Kevin', attendanceStatus: 'Present', score: 88 },
        { name: 'Laura', attendanceStatus: 'Absent', score: 55 },
        { name: 'Mallory', attendanceStatus: 'Present', score: 78 },
        { name: 'Niaj', attendanceStatus: 'Present', score: 82 },
        { name: 'Olivia', attendanceStatus: 'Absent', score: 72 },
        { name: 'Alice', attendanceStatus: 'Present', score: 90 },
        { name: 'Bob', attendanceStatus: 'Absent', score: 70 },
        { name: 'Charlie', attendanceStatus: 'Present', score: 85 },
        { name: 'David', attendanceStatus: 'Late', score: 60 },
        { name: 'Eve', attendanceStatus: 'Present', score: 95 },
        { name: 'Frank', attendanceStatus: 'Absent', score: 50 },
        { name: 'Grace', attendanceStatus: 'Present', score: 80 },
        { name: 'Heidi', attendanceStatus: 'Present', score: 75 },
        { name: 'Ivan', attendanceStatus: 'Absent', score: 40 },
        { name: 'Judy', attendanceStatus: 'Late', score: 65 },
        { name: 'Kevin', attendanceStatus: 'Present', score: 88 },
        { name: 'Laura', attendanceStatus: 'Absent', score: 55 },
        { name: 'Mallory', attendanceStatus: 'Present', score: 78 },
        { name: 'Niaj', attendanceStatus: 'Present', score: 82 },
        { name: 'Olivia', attendanceStatus: 'Absent', score: 72 },
    ],
    date: '2024-09-25'
};
